typography_spectrum: 0.78104
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 1
title: Revolutionary....
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.5087077864445746
  brandStrength: 0.103324503172189
  rhythmicContrast: 0.459113173186779
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#006eb2'
    - '#383431'
    - '#8c8c8c'
  lightness: 0.1058681623544544
purpose: []
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: MySpray Therapeutics
